name: Build, Validate, Deploy and Publish
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build and validate spec, then deploy and publish (only if push to main branch)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ github.event.pull_request.base.sha }}"
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-secondscreen/2022Apr/0007.html
          W3C_BUILD_OVERRIDE: |
            specStatus: CRD
